# Generated by Django 3.1.6 on 2021-02-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tilte',
            new_name='title',
        ),
    ]
